H10/DPRM.v, H10/Dio/dio_elem.v, H10/Dio/dio_rt_closure.v, H10/Dio/dio_single.v, H10/FRACTRAN_DIO.v, H10/Fractran/fractran_defs.v, H10/Fractran/fractran_dio.v, H10/Fractran/mm_fractran.v, H10/H10.v, H10/HALT_MM.v, H10/MM_FRACTRAN.v, Problems/Reduction.v, Shared/Libs/DLW/Utils/rel_iter.v, Shared/Libs/DLW/Utils/utils_list.v
Hi Yannick ... I propose a shortened proof of the backward simulation one step FRACTRAN -> one step MM. The trick is the one with functionality of FRACTRAN and totality of MM combined with one step forward. 
Also some improvements of the code for better corresp. with the paper.
Do you agree merging in wip ?
=> Mm fractran, simplified backward step proof

theories/H10/Dio/dio_bounded.v, theories/H10/Dio/dio_rt_closure.v, theories/H10/Fractran/fractran_dio.v, theories/H10/Matija/alpha.v, theories/H10/Matija/cipher.v, theories/Shared/Libs/DLW/Utils/utils_tac.v
Cleanup the `induction-on` tactic mess. remember induction-on revealed
a bug in `8.10.0`, hopefully getting fixed in `8.10.1` (see https://github.com/coq/coq/issues/10894)
Also remove unnecessary `Check` and `Print Assumptions` that were bloating the output of make all
The one should compile under `8.9.1` (I tested it)
=> Fixing the induction-on mess

theories/H10/DPRM.v, theories/H10/Fractran/mm_fractran.v, theories/H10/Fractran/mm_no_self.v, theories/ILL/Ll/eill_mm.v, theories/ILL/Mm/mm_comp.v, theories/ILL/Mm/mm_defs.v, theories/MM/env.v, theories/MM/mm_env_utils.v, theories/MM/mm_instr.v, theories/MM/mma_defs.v, theories/MuRec/ra_comp.v, theories/MuRec/ra_dio_poly.v, theories/MuRec/ra_enum.v, theories/MuRec/ra_mm.v, theories/MuRec/ra_mm_env.v, theories/MuRec/ra_utils.v, theories/MuRec/recalg.v, theories/Reductions/DIO_MUREC.v, theories/Reductions/MMA2_to_MM2.v, theories/Reductions/MM_to_MMA2.v, theories/Reductions/MUREC_MM.v, theories/_CoqProject
Notice that to avoid having several definitions of MM, I needed to generalize the definition of `mm_instr` to an arbitrary type `X : Type` of registers (in `MM/mm_instr.v`) of which only the instances `X = nat` and `X = pos n` are actually used. But this implied changing `mm_instr n` into `mm_instr (pos n)` at (not so many but still) several places in the code.
- `MM/env.v` : environments `env` to work with `mm_instr nat`; values of registers cannot be stored in a finitary vector `vec nat n` but need to be stored into `nat -> nat` instead
- `MM/mm_env_utils.v` : library for `env`
- `MM/mm_instr.v` : the general definition of `mm_instr X`; `MM/mma_defs.v` and `ILL/Mm/mm_defs.v` inherit/specialize this definition 
- `MuRec/recalg.v` : definition the type `recalg` of µ-recursive algorithms
- …
=> A BIG commit containing the DIO_SINGLE -> µ-REC -> MM reductions

theories/H10/ArithLibs/Zp.v, theories/H10/ArithLibs/lagrange.v, theories/H10/ArithLibs/luca.v, theories/H10/Dio/dio_binary.v, theories/H10/Dio/dio_bounded.v, theories/H10/Dio/dio_cipher.v, theories/H10/Dio/dio_elem.v, theories/H10/Dio/dio_expo.v, theories/H10/Dio/dio_logic.v, theories/H10/Dio/dio_rt_closure.v, theories/H10/FRACTRAN_DIO.v, theories/H10/Fractran/fractran_dio.v, theories/H10/H10.v, theories/H10/Matija/alpha.v, theories/Shared/Libs/DLW/Utils/gcd.v, theories/_CoqProject
Hi Yannick,
This is in preparation for the journal paper.
* I did reimplement `dio_form` so that atoms are just `x ≐ ⌞n⌟`, `x ≐ y`, `x ≐ y ⨢ z` and `x ≐ y ⨰ z` which allows for a much smoother reduction to `dio_elem`, both in the code which is now much nicer, and most importantly in the explanation part that is going to be included in the journal paper. 
* Also, I did strengthen the notion of Diophantine polynomial to that of _Diophantine function_ encoded as `dio_fun` and denoted `𝔻F`. Now we can work with arbitrary functions in Diophantine shapes, provided there is a Diophantine encoding of their graph. This allows for less cumbersome definitions.
* Finally a **major** cleanup of automation that is now very satisfactory ... basically, the new `dio auto` tactic fails nearly _nowhere_. 
* …
=> A fork for smoother reduction dio_form -> dio_elem

theories/L/Computability/MuRec.v, theories/L/Computability/Synthetic.v, theories/L/Datatypes/LSum.v, theories/L/Functions/Ackermann.v, theories/L/Reductions/MuRec.v, theories/MuRec/minimizer.v, theories/MuRec/ra_bs.v, theories/MuRec/ra_ca.v, theories/MuRec/ra_sem_eq.v, theories/MuRec/recursor.v, theories/_CoqProject
I've finished the reduction from mu-halting to lambda-halting.
Trickier than expected, because mu recursive functions are defined as a dependent type (not supported by L extraction) and there was no "simple" step-indexed evaluator. I've written one now and it extracts perfectly well to L, it's probably the most complicated example we ever tried the extraction on (that's also why it's slow).
There's one gap in `ra_ca.v` where I admitted something, otherwise I was able to port code easily from the ITP '17 repo of mu recursive functions.
=> Mu to lambda

theories/MuRec/ra_mm.v, theories/MuRec/ra_mm_env.v, theories/MuRec/ra_simul.v
Compile time should be far better. I did some changes with local impact in
- `MuRec/ra_mm_env.v`: simplified and renamed  `ra_compiled` and `ra_compiler_spec` into `ra_compiled`, `ra_compiler_spec` and `ra_compiler_stm`. 
Changed all `Let` into `Local Definition` to avoid polluting the proof environment. This was very negatively impacting the behaviour of the `omega` tactic (huge compile times).
- `MuRec/ra_mm.v`: a bit stronger statement for `ra_mm_compiler` explicitly giving the halting `PC` value.
- `MuRec/ra_simul.v`: slightly modified to account for the change of the statement of `ra_mm_compiler`.
=> Cleanup murec compiler, faster compile

theories/H10/DPRM.v, theories/H10/Fractran/prime_seq.v, theories/Shared/Libs/DLW/Utils/prime.v, theories/Shared/Libs/DLW/Utils/utils_tac.v
Hi Yannick,
I did update `DPRM.v` and the theorem `DPRM_n` so that it contains all the available equivalences: MM -> DIO_FORM -> DIO_ELEM -> DIO_SINGLE -> µ-rec -> MM at the level of _recognisable predicates_, not just undecidability. Hence we have provable equivalence of all these models.
FRACTRAN could be added but when recognising n-tuples (with n>1), you need a Gödel coding so even though it is a hidden intermediate step, it does not appear in the  `DPRM_n` theorem.
=> new version of the DPRM which shows all availalable equivalences

theories/H10/Fractran/mm_fractran.v, theories/H10/Fractran/prime_seq.v, theories/L/Reductions/H10_to_L.v, theories/L/Reductions/MuRec.v, theories/Shared/Libs/DLW/Utils/fin_bij.v, theories/Shared/Libs/DLW/Vec/pos.v, theories/Shared/Libs/DLW/Vec/vec.v, theories/TRAKHTENBROT/Sig1_1.v, theories/TRAKHTENBROT/Sign_Sig2.v, theories/TRAKHTENBROT/fo_logic.v, theories/TRAKHTENBROT/hfs.v
This is a PR to unify 
- `Fin.t` (from std lib) with `DLW/Vec/pos.pos`;
- `Vector.t` (from std lib) with `DLW/Vec/vec.vec`.
Not so many changes. For `pos` things went smoothly. For `vec`, it was more complicated because of several reasons:
- `Vector.cons X x n v` = `vec_cons X n x v` ie. arguments are not in the same order, which impacts the `induction` or `destruct` tactics with explicit intro patterns;
- `vec_cons` can no longer be seen as a constructor but the `_ ## _` notation can largely mitigate this;
- proof scripts that use auto-generated names are messed up because `induction v` will now behave as `induction v as [ | x n t ]` and not as `induction v as [ | n x v ]`. 
Might I advice everyone to _always introduce the names they use_ because correcting such migration bugs can become …
=> Unify Fin.t / pos and Vector.t / vec

theories/ILL/ILL_undec.v, theories/ILL/Reductions/iBPCP_MM.v, theories/MinskyMachines/MM/mm_comp.v, theories/MinskyMachines/MM/mm_comp_old.v, theories/MinskyMachines/MM_undec.v, theories/MinskyMachines/Reductions/BSM_MM.v, theories/MinskyMachines/Reductions/PCPb_to_MM.v, theories/Problems/BSM.v, theories/Reductions/BPCP_to_BSM.v, theories/StackMachines/BSM.v, theories/StackMachines/BSM/bsm_defs.v, theories/StackMachines/BSM/bsm_pcp.v, theories/StackMachines/BSM/bsm_utils.v, theories/StackMachines/BSM/tiles_solvable.v, theories/StackMachines/BSM_undec.v, theories/StackMachines/Reductions/iPCPb_to_BSM_HALTING.v, theories/_CoqProject
Migration:
+ `BinaryStackMachines` to the _existing_ `StackMachines` directory
+ removal of `omega`, replaced by `lia` in those moves files.
=> BinaryStackMachines to StackMachines

README.md
There's a `coq-8.12` branch now which I can compile locally, works on Travis and compiles on Andrej's Windows machine. I didn't use PRs to create it because there was nothing to merge against, so I'm opening this PR to have a central point for discussion.
The opam packages for `smpl` and the `base-library` are done. The official MetaCoq opam package is on its way, I created an internal version to make it easier to install. It's important to run `opam update` first, afterwards `opam install . --deps-only` should install the necessary packages.
There are some more warnings now, but not too many, I'll try to fix them in later PRs.
I'd also like to brush up the README a bit, feel free to mention relevant feedback here. I added the recent papers and fixed some links in the problems list.
We …
=> Branch for Coq 8.12

theories/Shared/FinTypeEquiv.v, theories/Shared/FinTypeForallExists.v, theories/StackMachines/Reductions/SBTM_to_BSM.v, theories/TM/Reductions/Arbitrary_to_Binary.v, theories/TM/Reductions/TM_to_SBTM.v, theories/TM/SBTM.v, theories/_CoqProject
I have an alphabet reduction from arbitrary alphabet to binary alphabet (reasonably easy, very nice application of the TM framework) and a simulation of single-tape binary Turing machines (`SBTM`) on binary stack machines (reasonably easy, very nice application of the `sss` framework). @DmxLarchey:The simulation uses 4 stacks: Left part of the tape, middle part of the tape, right part of the tape, and empty register for unconditional jumps. One can optimise middle away by merging it into the state space, but I didn't bother to, mainly because the compiler to MMs adds two counters anyways.
@mwuttke97 @fakusb The only thing that was slightly annoying me regarding TMs is that we do not have support to prove TMs total without actually talking about step indices. While one can abstract away …
=> Binary Turing machines and direct reduction from Turing machines to BSM

.travis.yml, Makefile, README.md, opam, theories/Makefile
This enables `make TIMED=1`, printing time information for every file. Travis is now using this option by default.
Also I changed the required MetaCoq package to the official `beta1` of MetaCoq. Nothing has to be done if you are on the old version though, they are compatible without any change.
Lastly, the CI shows up again in PRs thanks to a hint by @fakusb.
=> Timed option for make, new MetaCoq version

theories/H10/Dio/dio_logic.v, theories/MinskyMachines/MMenv/env.v, theories/TRAKHTENBROT/notations.v
Removes two kinds of _harmless_ warnings:
- `Coq` complaining about `Fixpoint` definitions that make no recursive sub-calls. `Fixpoint`s are somewhat natively better behaved wrt the `simpl` tactic. Solution is to replace by anonymous fixpoints, ie `Fixpoint foo ... := ...` is replaced with `Definition foo := fix foo ... := ...`;
- a component access notation `_ [ _ / _ ]` which what declared twice, once with the default (or absent) `format` directive, and a second time with a specific `format` directive to avoid unnecessary blank spaces, hence the warning.
The component access notation is declared as `Reserved Notation` in `Shared/Libs/DLW/Vec/vec.v` where it covers the case of `pos n` indexed vectors but also in `MinskyMachines/MMenv/env.v` where it covers `X -> Y` where `X` is a …
=> change Fixpoint to Definition ... := fix to avoid a warning

theories/FOL/Reductions/PCPb_to_FOL.v, theories/FOL/Reductions/PCPb_to_FOL_class.v, theories/FOL/Reductions/PCPb_to_FOL_intu.v, theories/H10/H10_undec.v, theories/ILL/CLL_undec.v, theories/ILL/ILL_undec.v, theories/ILL/Reductions/iBPCP_MM.v, theories/PCP/Reductions/HaltTM_1_to_PCPb.v, theories/Synthetic/Definitions.v, theories/Synthetic/InformativeDefinitions.v, theories/Synthetic/InformativeReducibilityFacts.v, theories/Synthetic/ReducibilityFacts.v, theories/Synthetic/SemiDecidabilityFacts.v, theories/Synthetic/Undecidability.v, theories/TRAKHTENBROT/decidable.v, theories/TRAKHTENBROT/enumerable.v, theories/TRAKHTENBROT/red_dec.v, theories/TRAKHTENBROT/red_undec.v, theories/TRAKHTENBROT/red_utils.v, theories/_CoqProject
- documented (via comments) synthetic definitions
- separated non-informative and informative definitions
- encapsulated (in Modules) non-essential notations
Closes the following point in #81 
> Cleaner, modular, commented synthetic definitions.
=> documented (via comments) synthetic definitions

theories/FRACTRAN/FRACTRAN/fractran_utils.v, theories/ILL/IMSELL.v, theories/ILL/Ll/imsell.v, theories/ILL/Reductions/ndMM2_IMSELL.v, theories/MinskyMachines/MM.v, theories/MinskyMachines/MMA/fractran_mma.v, theories/MinskyMachines/MMA/mma_defs.v, theories/MinskyMachines/MMA/mma_simul.v, theories/MinskyMachines/MMA/mma_utils.v, theories/MinskyMachines/MMA2_undec.v, theories/MinskyMachines/MMenv/mme_utils.v, theories/MinskyMachines/Reductions/FRACTRAN_to_MMA2.v, theories/MinskyMachines/Reductions/MMA2_to_ndMM2_ACCEPT.v, theories/MinskyMachines/Reductions/MM_to_MMA2.v, theories/MinskyMachines/ndMM2.v, theories/MinskyMachines/ndMM2_undec.v, theories/MuRec/ra_mm_env.v, theories/Shared/Libs/DLW/Code/sss.v, theories/Shared/Libs/DLW/Code/subcode.v, theories/StackMachines/BSM/bsm_utils.v, theories/StackMachines/Util/SMN_transform.v, theories/_CoqProject
This PR provides improvements to the `IMSELL` undecidability results code. I would like it to be merged quickly so that I can refer to it in the final version of the upcoming FSCD21 paper [pre-print](https://members.loria.fr/DLarchey/files/papers/fscd21.pdf) that presents this work and also the _previously undocumented_ reduction from `FRACTRAN` to `MMA(2)` and `MMA0(2)` (two counters alternate Minsky machines). 
Also some updates to the library code:
+ improved `subcode_tac` in `Shared/Libs/DLW/Code/subcode.v` to solve more subcode detection automatically. Some proofs get a bit simplified in the `MM` and `BSM` code, ie. `subcode_tac; ...` is removed on many occasions in eg `StackMachines/BSM/bsm_utils.v` and `MuRec/ra_mm_env.v`;
+ better notations for alternate `MM` (ie. `INCₐ` instead …
=> Improvements (notations, shorter proofs, etc) for IMSELL

theories/CounterMachines/CM2.v, theories/CounterMachines/CM2_dec.v, theories/CounterMachines/Deciders/CM2_REV_HALT_dec.v, theories/CounterMachines/Deciders/CM2_REV_dec.v, theories/CounterMachines/Deciders/CM2_UBOUNDED_dec.v, theories/CounterMachines/Deciders/CM2_UMORTAL_dec.v, theories/CounterMachines/Reductions/CM2_HALT_to_CM1_HALT.v, theories/CounterMachines/Reductions/MM2_HALTING_to_CM2_HALT.v, theories/CounterMachines/Util/CM2_facts.v, theories/CounterMachines/Util/Facts.v, theories/MinskyMachines/Deciders/MM_2_HALTING_dec.v, theories/MinskyMachines/Deciders/MPM2_HALT_dec.v, theories/MinskyMachines/MM.v, theories/MinskyMachines/MM_dec.v, theories/StringRewriting/Reductions/CM2_HALT_to_SSTS01/CM2_HALT_to_SR2ab.v, theories/Synthetic/Definitions.v, theories/_CoqProject
While decidability of Uniform Mortality (and relatedly Uniform Boundedness) for Two-counter Machines is known [1], decidability of Reversible Two-counter Machine (`Cm2`) Halting contrasts a known negative result [2].
[1] Kari, Jarkko, and Nicolas Ollinger. "Periodicity and immortality in reversible computing." International Symposium on Mathematical Foundations of Computer Science. Springer, Berlin, Heidelberg, 2008.
[2] Morita, Kenichi. "Universality of a reversible two-counter machine." Theoretical Computer Science 168.2 (1996): 303-320.
This work implements deciders for Uniform Boundedness, Uniform Mortality, and Reversible Halting for `Cm2`; full list of changes below.
- simplified CM2 definition
- added problems
- Two-counter Machine Reversibility (`CM2_REV`)
- Reversible Two-counter …
=> CM2 decision procedures

README.md
This just adds a missing reference. No code update.
=> update the README file for including FSCD 2021 on IMSELL

theories/FRACTRAN/Deciders/Halt_REV_FRACTRAN_dec.v, theories/FRACTRAN/FRACTRAN.v, theories/FRACTRAN/FRACTRAN_dec.v, theories/_CoqProject
Based on code in the master's thesis by @archbung.
Small changes to the original code include:
- compatibility with `Set Default Goal Selector "!"`
- compatibility with `Set Mangle Names`
- explicit boolean decision procedure `decide : { P : list (nat * nat) | fractran_reversible P } * nat -> bool`, which is stronger than `exists f, ...`
- top-level `FRACTRAN_dec.v` result
- included @DmxLarchey as author because of remarks and ideas in an early private communication
Also fixed a copy-paste typo "autor", which is why many files are touched.
=> Added decider for reversible FRACTRAN halting

theories/StringRewriting/PCSnf.v, theories/StringRewriting/SR.v, theories/StringRewriting/Util/Definitions.v
changed `Definition string X := list X.` into `Notation string X := (list X).`
This solve the universe inconsistency arising from:
```coq
Require Undecidability.L.Datatypes.LFinType.
Require Undecidability.StringRewriting.Reductions.SBTM_HALT_to_TSR.
Require Undecidability.TM.Basic.Mono.
```
=> removed a universe inconsistency

theories/ILL/Reductions/iBPCP_MM.v, theories/MuRec/Reductions/Diophantine_to_MuRec_computable.v, theories/PCP/Reductions/HaltTM_1_to_PCPb.v, theories/StackMachines/BSM/bsm_pctm.v, theories/StackMachines/Reductions/PCTM_HALT_to_BSM_HALTING.v, theories/Synthetic/ReducibilityFacts.v, theories/Synthetic/Undecidability.v, theories/TM/PCTM/pctm_sbtm.v, theories/TM/Reductions/SBTM_HALT_to_PCTM_HALT.v
In [25f8d98a](https://github.com/uds-psl/coq-library-undecidability/commit/25f8d98a151233c473af4cd87c22aa31a63d8306), @mrhaandi 
> established that intermediate files do not depend on _undec files
> do not unnecessarily `Require Synthetic.Undecidability`
It seems like a few files where forgotten. A quick dependency graph DFS suggests that the following files still depend on `Synthetic.Undecidability` while not being named `_undec`:
```
theories/ILL/Reductions/iBPCP_MM
theories/MinskyMachines/Reductions/SBTM_to_MMA2_HALTING
theories/MuRec/Reductions/Diophantine_to_MuRec_computable
theories/PCP/Reductions/HaltTM_1_to_PCPb
theories/StackMachines/BSM/bsm_pctm
theories/StackMachines/Reductions/PCTM_HALT_to_BSM_HALTING
theories/Synthetic/Models_Equivalent
theories/Synthetic/Undecidability …
```
=> Remove dependency on Synthetic.Undecidability for non-_undec files

theories/TM/Single/StepTM.v
Improve compilation of `TM/Single/StepTM.v` from
`TM/Single/StepTM.vo (real: 12.93, user: 12.80, sys: 0.11, mem: 573864 ko)`
to
`TM/Single/StepTM.vo (real: 7.41, user: 7.31, sys: 0.08, mem: 535524 ko)`
by changing one `Notation` to `Definition` for smaller proof terms.
=> improve performance of TM/Single/StepTM.v

README.md, theories/LambdaCalculus/HOMatching.v, theories/LambdaCalculus/HOMatching_undec.v, theories/LambdaCalculus/Reductions/HaltLclosed_to_wCBNclosed.v, theories/LambdaCalculus/Reductions/SSTS01_to_HOMbeta.v, theories/LambdaCalculus/Util/confluence.v, theories/LambdaCalculus/Util/facts.v, theories/LambdaCalculus/Util/stlc_facts.v, theories/LambdaCalculus/Util/term_facts.v, theories/_CoqProject
- added higher-order matching wrt. beta-equivalence `HOMbeta` 
- added reduction from `SSTS01` to `HOMbeta` resulting in `undecidable HOMbeta`
The reduction is quite different from the known technique by Loader [1].
It is based on the technique used for intersection type inhabitation, see `IntersectionTypes/Reductions/SSTS01_to_CD_INH.v`, sharing a common seed. A write up for a potential publication is in progress.
[1] Loader, Ralph. "Higher order β-matching is undecidable." Logic Journal of the IGPL 11.1 (2003): 51-68.
=> Higher-order beta-matching
